# .goreleaser.yml
project_name: DevOpsBot
before:
  hooks:
    - go mod download
builds:
  - binary: devops-bot
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X main.version={{.Version}}
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
archives:
  - wrap_in_directory: true
