name: build

on: [push]

jobs:
  mod:
    name: Mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: go mod download

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [mod]
    env:
      CGO_ENABLED: "0"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: go build
