name: build

on: [push]

jobs:
  mod:
    name: Mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
      - run: go mod download

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [mod]
    env:
      CGO_ENABLED: "0"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
      - run: go build
